### ISSUE TITLE
In v1.1.3, trace_block rpc is not working in specific block number

### ISSUE THREAD

**Issue by sjlee1125** [node-real/bsc-erigon#151]
#### System information

Erigon version: v1.1.3

OS & Version: Linux

Commit hash: 

Erigon Command (with flags/config):erigon
--datadir=./data
--chain=chapel
--http.addr=0.0.0.0
--http.port=8545
--http.corsdomain=*
--ws
--http.vhosts=*
--http.api=eth,net,trace,web3,erigon
--snapshots=true
--torrent.download.rate=200mb

####rpc body
```
{
    "jsonrpc": "2.0",
    "method": "trace_block",
    "id": 1000,
    "params": ["31103038"]
}
```

#### response
```
{
    "jsonrpc": "2.0",
    "id": 1000,
    "error": {
        "code": -32000,
        "message": "convert tx into msg: eip-1559 transactions require London"
    }
}
```

**Comment by calmbeing** [comment]
Can you confirm your request and local node to provide more information, because it can return the correct result in our local env:
`curl localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"trace_block","params":["0x1DA983E"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":[{"action":{"from":"0xbbaf56e3b9b9c452e202f1e16eae5d4667162473","callType":"call","gas":"0x0","input":"0x0f98b6e847025e99d47eef751ab192621cf02dd000000000000000000000000091d18e54daf4f677cb28167158d6dd21f6ab3921000000000000000000000000bbaf56e3b9b9c452e202f1e16eae5d46671624730000000000000000000000000000000000000000000000000000000000000000","to":"0x7c125c1d515b8945841b3d5144a060115c58725f","value":"0x4f0c41d240a0000"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x9c775c901ecbbeb9f20782caf363186c994a39ac971ae0d2edbcf8797e6c81ec","transactionPosition":0,"type":"call"},{"action":{"from":"0x661fded5665e1bd8c1421ce5a129ef3f07aea1fc","callType":"call","gas":"0x62f2","input":"0x095ea7b30000000000000000000000008ce3326c596e9eb070e11bbdec08b3bbb44a015f00000000000000000000000000000000000000000000010f0cf064dd59200000","to":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x62f2","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[],"transactionHash":"0x5478bd47bf0079d2ae584e23f56f6436a9d0c1827d9a1106a8a6b2e87177b10e","transactionPosition":1,"type":"call"},{"action":{"from":"0x63e4c2225fec1a4ce637abee0175642353cb4f90","callType":"call","gas":"0x146b6","input":"0x2f4f21e200000000000000000000000063e4c2225fec1a4ce637abee0175642353cb4f900000000000000000000000000000000000000000000000015af1d78b58c40000","to":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x12153","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":2,"traceAddress":[],"transactionHash":"0xe4d3b0eb73cb1f2829d2763d0ca6251210897220475e3cae85f97bd3b4ad7328","transactionPosition":2,"type":"call"},{"action":{"from":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","callType":"staticcall","gas":"0x13c0c","input":"0x4337650f00000000000000000000000063e4c2225fec1a4ce637abee0175642353cb4f900000000000000000000000000000000000000000000000015af1d78b58c400000000000000000000000000000000000000000000000000000000000000000001","to":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x1944","output":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000015af1d78b58c40000"},"subtraces":0,"traceAddress":[0],"transactionHash":"0xe4d3b0eb73cb1f2829d2763d0ca6251210897220475e3cae85f97bd3b4ad7328","transactionPosition":2,"type":"call"},{"action":{"from":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","callType":"call","gas":"0x835d","input":"0x23b872dd00000000000000000000000063e4c2225fec1a4ce637abee0175642353cb4f900000000000000000000000001b3eb089cb7aaee3c119091ce291590f464eb6a50000000000000000000000000000000000000000000000015af1d78b58c40000","to":"0xc112217a5b0f83eefdd7e6edf7c08013de6409b0","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x5ccb","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[1],"transactionHash":"0xe4d3b0eb73cb1f2829d2763d0ca6251210897220475e3cae85f97bd3b4ad7328","transactionPosition":2,"type":"call"},{"action":{"from":"0x059887398233b9b9609c44f692a0e38f0569228b","callType":"call","gas":"0x46114","input":"0x52ef348a0000000000000000000000000000000000000000000000056bc75e2d63100000","to":"0xaf83d1311114d5883a8378b856bdb179ba640eec","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x315ff","output":"0x"},"subtraces":1,"traceAddress":[],"transactionHash":"0x6ff53e259f1e02f458e12ff850a55d223b2ea34b281524579e169890bb16d3e1","transactionPosition":3,"type":"call"},{"action":{"from":"0xaf83d1311114d5883a8378b856bdb179ba640eec","callType":"call","gas":"0x40650","input":"0x23b872dd000000000000000000000000059887398233b9b9609c44f692a0e38f0569228b000000000000000000000000af83d1311114d5883a8378b856bdb179ba640eec0000000000000000000000000000000000000000000000000de0b6b3a7640000","to":"0xac7a54f94f52fae3b7165792f56b829dd63dd756","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x5114","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x6ff53e259f1e02f458e12ff850a55d223b2ea34b281524579e169890bb16d3e1","transactionPosition":3,"type":"call"},{"action":{"from":"0x8936b8860376c0de8e62231d3794eb26eb64598f","callType":"call","gas":"0x0","input":"0x","to":"0xda9dd55d2264dd63256c571c3eb3a2baac62bde9","value":"0x6ed4c46a48b3000"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x5ed96f329e8ff943f3167c36b8c39a020ebe7bc42f44c1f4af1f42cb3687317e","transactionPosition":4,"type":"call"},{"action":{"from":"0x679612e2df5b481428053c91c39194ea5ff3aab2","callType":"call","gas":"0x820e","input":"0xc6c3bbe6000000000000000000000000c112217a5b0f83eefdd7e6edf7c08013de6409b0000000000000000000000000679612e2df5b481428053c91c39194ea5ff3aab20000000000000000000000000000000000000000000000056bc75e2d63100000","to":"0xba9bd463db32ba67954568ee25531e273ef1db52","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x6d7c","output":"0x"},"subtraces":1,"traceAddress":[],"transactionHash":"0x58d7a4ca2ede731c15384b11363e399417ec6f7d7df72bea1ca8bcc85d1479c5","transactionPosition":5,"type":"call"},{"action":{"from":"0xba9bd463db32ba67954568ee25531e273ef1db52","callType":"call","gas":"0x59fe","input":"0x40c10f19000000000000000000000000679612e2df5b481428053c91c39194ea5ff3aab20000000000000000000000000000000000000000000000056bc75e2d63100000","to":"0xc112217a5b0f83eefdd7e6edf7c08013de6409b0","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x46a9","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x58d7a4ca2ede731c15384b11363e399417ec6f7d7df72bea1ca8bcc85d1479c5","transactionPosition":5,"type":"call"},{"action":{"from":"0x66fed255e376c5e5495384a8abc01a1aa65afe8a","callType":"call","gas":"0x2661","input":"0xecc0261c000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000138810000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000175af44000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000b2d05e00","to":"0xa60d3b6d5e00907621cacfbfb6de39068d0858ed","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"error":"out of gas","result":null,"subtraces":0,"traceAddress":[],"transactionHash":"0xf1dcc8dc41a60da25c4d65d09ec3707bdb2cce6d759cd7c611ddf413aea79bea","transactionPosition":6,"type":"call"},{"action":{"from":"0x66fed255e376c5e5495384a8abc01a1aa65afe8a","callType":"call","gas":"0x2025","input":"0x9daf96ff0000000000000000000000000000000000000000000000000000000000000001","to":"0x53b2566af310554ab6594e8ef30d3dc8efce4ba7","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x1a49","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x44f183932c87ed5e9383a08cb9fdeb5763a0f587bf94cc5737a4659e54050b05","transactionPosition":7,"type":"call"},{"action":{"from":"0x1284214b9b9c85549ab3d2b972df0deef66ac2c9","callType":"call","gas":"0x1dcd12f8","input":"0x","to":"0x0000000000000000000000000000000000001002","value":"0x4823a54194960"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x5ec","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x6367e9337bd0633c707173d4f681ae31f3a13c95bf3dad38412e7cdc14312515","transactionPosition":8,"type":"call"},{"action":{"from":"0x1284214b9b9c85549ab3d2b972df0deef66ac2c9","callType":"call","gas":"0x1dcd1148","input":"0xf340fa010000000000000000000000001284214b9b9c85549ab3d2b972df0deef66ac2c9","to":"0x0000000000000000000000000000000000001000","value":"0x43a16aed7b4ca0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x8d90","output":"0x"},"subtraces":1,"traceAddress":[],"transactionHash":"0xfa611a6b202a4c3ddf56472a665d6c5a9daf0d75ec1d7ea98ac3401820db73d5","transactionPosition":9,"type":"call"},{"action":{"from":"0x0000000000000000000000000000000000001000","callType":"call","gas":"0x8fc","input":"0x","to":"0x000000000000000000000000000000000000dead","value":"0x6c3577e25ee10"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0xfa611a6b202a4c3ddf56472a665d6c5a9daf0d75ec1d7ea98ac3401820db73d5","transactionPosition":9,"type":"call"},{"action":{"author":"0x1284214b9b9c85549ab3d2b972df0deef66ac2c9","rewardType":"block","value":"0x1bc16d674ec80000"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":null,"subtraces":0,"traceAddress":[],"type":"reward"}]}`

**Comment by sjlee1125** [comment]
result:
```
curl localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"trace_block","params":["0x1DA983E"],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"convert tx into msg: eip-1559 transactions require London"}}
```


Some blocks encounter errors while others succeed.

**Comment by blxdyx** [comment]
The same command.
`curl localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"trace_block","params":["0x1DA983E"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":[{"action":{"from":"0xbbaf56e3b9b9c452e202f1e16eae5d4667162473","callType":"call","gas":"0x0","input":"0x0f98b6e847025e99d47eef751ab192621cf02dd000000000000000000000000091d18e54daf4f677cb28167158d6dd21f6ab3921000000000000000000000000bbaf56e3b9b9c452e202f1e16eae5d46671624730000000000000000000000000000000000000000000000000000000000000000","to":"0x7c125c1d515b8945841b3d5144a060115c58725f","value":"0x4f0c41d240a0000"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x9c775c901ecbbeb9f20782caf363186c994a39ac971ae0d2edbcf8797e6c81ec","transactionPosition":0,"type":"call"},{"action":{"from":"0x661fded5665e1bd8c1421ce5a129ef3f07aea1fc","callType":"call","gas":"0x62f2","input":"0x095ea7b30000000000000000000000008ce3326c596e9eb070e11bbdec08b3bbb44a015f00000000000000000000000000000000000000000000010f0cf064dd59200000","to":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x62f2","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[],"transactionHash":"0x5478bd47bf0079d2ae584e23f56f6436a9d0c1827d9a1106a8a6b2e87177b10e","transactionPosition":1,"type":"call"},{"action":{"from":"0x63e4c2225fec1a4ce637abee0175642353cb4f90","callType":"call","gas":"0x146b6","input":"0x2f4f21e200000000000000000000000063e4c2225fec1a4ce637abee0175642353cb4f900000000000000000000000000000000000000000000000015af1d78b58c40000","to":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x12153","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":2,"traceAddress":[],"transactionHash":"0xe4d3b0eb73cb1f2829d2763d0ca6251210897220475e3cae85f97bd3b4ad7328","transactionPosition":2,"type":"call"},{"action":{"from":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","callType":"staticcall","gas":"0x13c0c","input":"0x4337650f00000000000000000000000063e4c2225fec1a4ce637abee0175642353cb4f900000000000000000000000000000000000000000000000015af1d78b58c400000000000000000000000000000000000000000000000000000000000000000001","to":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x1944","output":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000015af1d78b58c40000"},"subtraces":0,"traceAddress":[0],"transactionHash":"0xe4d3b0eb73cb1f2829d2763d0ca6251210897220475e3cae85f97bd3b4ad7328","transactionPosition":2,"type":"call"},{"action":{"from":"0x1b3eb089cb7aaee3c119091ce291590f464eb6a5","callType":"call","gas":"0x835d","input":"0x23b872dd00000000000000000000000063e4c2225fec1a4ce637abee0175642353cb4f900000000000000000000000001b3eb089cb7aaee3c119091ce291590f464eb6a50000000000000000000000000000000000000000000000015af1d78b58c40000","to":"0xc112217a5b0f83eefdd7e6edf7c08013de6409b0","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x5ccb","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[1],"transactionHash":"0xe4d3b0eb73cb1f2829d2763d0ca6251210897220475e3cae85f97bd3b4ad7328","transactionPosition":2,"type":"call"},{"action":{"from":"0x059887398233b9b9609c44f692a0e38f0569228b","callType":"call","gas":"0x46114","input":"0x52ef348a0000000000000000000000000000000000000000000000056bc75e2d63100000","to":"0xaf83d1311114d5883a8378b856bdb179ba640eec","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x315ff","output":"0x"},"subtraces":1,"traceAddress":[],"transactionHash":"0x6ff53e259f1e02f458e12ff850a55d223b2ea34b281524579e169890bb16d3e1","transactionPosition":3,"type":"call"},{"action":{"from":"0xaf83d1311114d5883a8378b856bdb179ba640eec","callType":"call","gas":"0x40650","input":"0x23b872dd000000000000000000000000059887398233b9b9609c44f692a0e38f0569228b000000000000000000000000af83d1311114d5883a8378b856bdb179ba640eec0000000000000000000000000000000000000000000000000de0b6b3a7640000","to":"0xac7a54f94f52fae3b7165792f56b829dd63dd756","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x5114","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x6ff53e259f1e02f458e12ff850a55d223b2ea34b281524579e169890bb16d3e1","transactionPosition":3,"type":"call"},{"action":{"from":"0x8936b8860376c0de8e62231d3794eb26eb64598f","callType":"call","gas":"0x0","input":"0x","to":"0xda9dd55d2264dd63256c571c3eb3a2baac62bde9","value":"0x6ed4c46a48b3000"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x5ed96f329e8ff943f3167c36b8c39a020ebe7bc42f44c1f4af1f42cb3687317e","transactionPosition":4,"type":"call"},{"action":{"from":"0x679612e2df5b481428053c91c39194ea5ff3aab2","callType":"call","gas":"0x820e","input":"0xc6c3bbe6000000000000000000000000c112217a5b0f83eefdd7e6edf7c08013de6409b0000000000000000000000000679612e2df5b481428053c91c39194ea5ff3aab20000000000000000000000000000000000000000000000056bc75e2d63100000","to":"0xba9bd463db32ba67954568ee25531e273ef1db52","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x6d7c","output":"0x"},"subtraces":1,"traceAddress":[],"transactionHash":"0x58d7a4ca2ede731c15384b11363e399417ec6f7d7df72bea1ca8bcc85d1479c5","transactionPosition":5,"type":"call"},{"action":{"from":"0xba9bd463db32ba67954568ee25531e273ef1db52","callType":"call","gas":"0x59fe","input":"0x40c10f19000000000000000000000000679612e2df5b481428053c91c39194ea5ff3aab20000000000000000000000000000000000000000000000056bc75e2d63100000","to":"0xc112217a5b0f83eefdd7e6edf7c08013de6409b0","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x46a9","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0x58d7a4ca2ede731c15384b11363e399417ec6f7d7df72bea1ca8bcc85d1479c5","transactionPosition":5,"type":"call"},{"action":{"from":"0x66fed255e376c5e5495384a8abc01a1aa65afe8a","callType":"call","gas":"0x2661","input":"0xecc0261c000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000138810000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000175af44000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000b2d05e00","to":"0xa60d3b6d5e00907621cacfbfb6de39068d0858ed","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"error":"out of gas","result":null,"subtraces":0,"traceAddress":[],"transactionHash":"0xf1dcc8dc41a60da25c4d65d09ec3707bdb2cce6d759cd7c611ddf413aea79bea","transactionPosition":6,"type":"call"},{"action":{"from":"0x66fed255e376c5e5495384a8abc01a1aa65afe8a","callType":"call","gas":"0x2025","input":"0x9daf96ff0000000000000000000000000000000000000000000000000000000000000001","to":"0x53b2566af310554ab6594e8ef30d3dc8efce4ba7","value":"0x0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x1a49","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x44f183932c87ed5e9383a08cb9fdeb5763a0f587bf94cc5737a4659e54050b05","transactionPosition":7,"type":"call"},{"action":{"from":"0x1284214b9b9c85549ab3d2b972df0deef66ac2c9","callType":"call","gas":"0x1dcd12f8","input":"0x","to":"0x0000000000000000000000000000000000001002","value":"0x4823a54194960"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x5ec","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x6367e9337bd0633c707173d4f681ae31f3a13c95bf3dad38412e7cdc14312515","transactionPosition":8,"type":"call"},{"action":{"from":"0x1284214b9b9c85549ab3d2b972df0deef66ac2c9","callType":"call","gas":"0x1dcd1148","input":"0xf340fa010000000000000000000000001284214b9b9c85549ab3d2b972df0deef66ac2c9","to":"0x0000000000000000000000000000000000001000","value":"0x43a16aed7b4ca0"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x8d90","output":"0x"},"subtraces":1,"traceAddress":[],"transactionHash":"0xfa611a6b202a4c3ddf56472a665d6c5a9daf0d75ec1d7ea98ac3401820db73d5","transactionPosition":9,"type":"call"},{"action":{"from":"0x0000000000000000000000000000000000001000","callType":"call","gas":"0x8fc","input":"0x","to":"0x000000000000000000000000000000000000dead","value":"0x6c3577e25ee10"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[0],"transactionHash":"0xfa611a6b202a4c3ddf56472a665d6c5a9daf0d75ec1d7ea98ac3401820db73d5","transactionPosition":9,"type":"call"},{"action":{"author":"0x1284214b9b9c85549ab3d2b972df0deef66ac2c9","rewardType":"block","value":"0x1bc16d674ec80000"},"blockHash":"0x3f0d4f8da3f82882aacab921987a53823ab123f88abe1386c1d8cc8621e219e7","blockNumber":31103038,"result":null,"subtraces":0,"traceAddress":[],"type":"reward"}]}`

**Comment by sjlee1125** [comment]
t

if transaction is eip 1559 type, error occur
```
{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0xf91435ec94025a5ca21569e6f4a9c2180a94ae4d5bc0a3baf93c53eecd0a9830"],
    "id":67
}
```

result:
```
{
    "jsonrpc": "2.0",
    "id": 67,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}
```

How can i fix it?

**Comment by blxdyx** [comment]
It test fine. Have you set --prune flags before?  It's a good choice to use the[ testnet snapshot](https://github.com/bnb-chain/bsc-snapshots)
<img width="1465" alt="image" src="https://github.com/node-real/bsc-erigon/assets/125243069/85b360d7-8d2b-4922-9e81-91c477238be0">

**Comment by blxdyx** [comment]
Maybe the malformed JSON? Its my command:
 `curl --location --request POST 'localhost:8545/' \
--header 'content-type: application/json' \
--data-raw '[{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0xf91435ec94025a5ca21569e6f4a9c2180a94ae4d5bc0a3baf93c53eecd0a9830"],
    "id":67
}]'`

**Comment by sjlee1125** [comment]
Thank you for providing testnet snapshot. I runned node from the snapshot. it worked!

**Comment by calmbeing** [comment]
Closed, please reopen if any further problem
